### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ynunokawa** [ynunokawa/esri-react-js#1]
- [x] Highlighting selected row and feature when onMouseOver
- [x] Setting automatically columns with looping a array which contain attributes
- [x] add a dropdown select to set a layer
- [x] creating as AMD module (Compiled JS)

**Comment by ynunokawa** [comment]
https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=require(%5B%0A%09'esri%2Farcgis%2Futils'%2C%0A%09'dojo%2F_base%2Farray'%2C%0A%0A%09'react'%2C%0A%09'reactDom'%2C%0A%09'fixedDataTable'%0A%5D%2C%20function(%0A%09arcgisUtils%2C%0A%09arrayUtils%2C%0A%0A%09React%2C%0A%09ReactDOM%2C%0A%09FixedDataTable%0A)%20%7B%0A%0A%09%2F%2F%20Grobal%0A%09var%20map%3B%0A%09var%20layer%3B%0A%0A%09var%20featureId%20%3D%20'LOCATIONID'%3B%0A%09var%20attributesForTable%20%3D%20%5B%7B%0A%09%09name%3A%20'LOCATIONID'%2C%0A%09%09label%3A%20'Name'%0A%09%7D%2C%20%7B%0A%09%09name%3A%20'NUMSPACES'%2C%0A%09%09label%3A%20'Capacity'%0A%09%7D%5D%3B%0A%09var%20mapId%20%3D%20'1c0bf2bf70244f888361280f4aabde94'%3B%0A%09var%20layerId%20%3D%20'Bike_Parking_4640'%3B%0A%0A%09var%20rows%20%3D%20%5B%5D%3B%0A%20%20%09var%20Table%20%3D%20FixedDataTable.Table%3B%0A%09var%20Column%20%3D%20FixedDataTable.Column%3B%0A%0A%09%2F%2F%20Esri%20Map%0A%09var%20mapDeferred%20%3D%20arcgisUtils.createMap(mapId%2C%20'mapDiv')%3B%0A%09mapDeferred.then(function(response)%20%7B%0A%09%09map%20%3D%20response.map%3B%0A%09%09console.log(map)%3B%0A%09%09layer%20%3D%20map.getLayer(layerId)%3B%0A%09%09console.log(layer)%3B%0A%0A%09%09setTimeout(function()%20%7B%0A%09%09%09%2F%2F%20EsriFixedDataTable%0A%09%09%09initEsriFixedDataTable()%3B%0A%09%09%7D%2C%20500)%3B%0A%09%7D)%3B%0A%0A%09%2F%2F%20React%20Startup%20Codes%20(JSX)%0A%09ReactDOM.render(%0A%09%20%20%20%20%3Ch1%3EHello%2C%20React!%3C%2Fh1%3E%2C%0A%09%20%20%20%20document.getElementById('example')%0A%20%20%09)%3B%0A%0A%0A%20%20%09%2F%2F**%20EsriJS%20%2B%20FixedDataTable%20(JSX)%20**%2F%2F%0A%0A%09function%20getFeatureAttributes(layer%2C%20extent)%20%7B%0A%09%09var%20setRows%20%3D%20%5B%5D%3B%0A%09%09console.log('getFeatureAttributes')%3B%0A%09%09arrayUtils.forEach(layer.graphics%2C%20function(g)%20%7B%0A%09%09%09if(extent.contains(g.geometry))%20%7B%0A%09%09%09%09setRows.push(%5Bg.attributes%5BattributesForTable%5B0%5D.name%5D%2C%20g.attributes%5BattributesForTable%5B1%5D.name%5D%5D)%3B%0A%09%09%09%7D%0A%09%09%7D)%3B%0A%09%09console.log('updatedRowsCount%3A%20'%2C%20setRows.length)%3B%0A%09%09return%20setRows%3B%0A%09%7D%0A%0A%09function%20getTargetFeature(id)%20%7B%0A%09%09arrayUtils.forEach(layer.graphics%2C%20function(g)%20%7B%0A%09%09%09if(g.attributes%5BfeatureId%5D%20%3D%3D%3D%20id)%20%7B%0A%09%09%09%09map.centerAndZoom(g.geometry%2C%2016)%3B%0A%09%09%09%7D%0A%09%09%7D)%3B%0A%09%7D%0A%0A%09function%20initEsriFixedDataTable()%20%7B%0A%09%09console.log(layer)%3B%0A%09%09var%20EsriFixedDataTable%20%3D%20React.createClass(%7B%0A%09%09%09getInitialState()%20%7B%0A%09%09%09%09return%20%7B%0A%09%09%09%09%09rows%20%3A%20getFeatureAttributes(layer%2C%20map.extent)%0A%09%09%09%09%7D%3B%0A%09%09%09%7D%2C%0A%0A%09%09%09_rowGetter(rowIndex)%20%7B%0A%09%09%09%09return%20this.state.rows%5BrowIndex%5D%3B%0A%09%09%09%7D%2C%0A%0A%09%09%09_onRowSelect%3A%20function(e%2C%20index)%20%7B%0A%09%09%09%09console.log(e%2C%20index)%3B%0A%09%09%09%09console.log(this.state.rows%5Bindex%5D%5B0%5D)%3B%0A%09%09%09%09getTargetFeature(this.state.rows%5Bindex%5D%5B0%5D)%3B%0A%09%09%09%7D%2C%0A%0A%09%09%09componentDidMount%3A%20function()%20%7B%0A%09%09%09%09this.props.map.on('extent-change'%2C%20function(e)%20%7B%0A%09%09%09%09%09this.setState(%7B%20rows%3A%20getFeatureAttributes(layer%2C%20e.extent)%20%7D)%3B%0A%09%09%09%09%7D.bind(this))%3B%0A%09%09%20%20%09%7D%2C%0A%0A%09%09%09render()%20%7B%0A%09%09%09%09return%20(%0A%09%09%09%20%20%20%20%20%20%3CTable%0A%09%09%09%09%20%20%20%20rowHeight%3D%7B30%7D%0A%09%09%09%09%20%20%20%20rowGetter%3D%7Bthis._rowGetter%7D%0A%09%09%09%09%20%20%20%20rowsCount%3D%7Bthis.state.rows.length%7D%0A%09%09%09%09%20%20%20%20width%3D%7B5000%7D%0A%09%09%09%09%20%20%20%20height%3D%7B300%7D%0A%09%09%09%09%20%20%20%20headerHeight%3D%7B50%7D%0A%09%09%09%09%20%20%20%20onRowClick%3D%7Bthis._onRowSelect%7D%3E%0A%09%09%09%09%20%20%20%20%3CColumn%0A%09%09%09%09%20%20%20%20%20%20label%3D%7BattributesForTable%5B0%5D.label%7D%0A%09%09%09%09%20%20%20%20%20%20width%3D%7B300%7D%0A%09%09%09%09%20%20%20%20%20%20dataKey%3D%7B0%7D%0A%09%09%09%09%20%20%20%20%2F%3E%0A%09%09%09%09%20%20%20%20%3CColumn%0A%09%09%09%09%20%20%20%20%20%20label%3D%7BattributesForTable%5B1%5D.label%7D%0A%09%09%09%09%20%20%20%20%20%20width%3D%7B500%7D%0A%09%09%09%09%20%20%20%20%20%20dataKey%3D%7B1%7D%0A%09%09%09%09%20%20%20%20%2F%3E%0A%09%09%09%09%20%20%3C%2FTable%3E%0A%09%09%09%20%20%20%20)%0A%09%09%09%7D%2C%0A%09%09%7D)%3B%0A%0A%09%09ReactDOM.render(%0A%09%09%09%3CEsriFixedDataTable%20map%3D%7Bmap%7D%20%2F%3E%2C%0A%09%09%09document.getElementById('example2')%0A%09%09)%3B%0A%0A%09%7D%0A%0A%7D)%3B

**Comment by ynunokawa** [comment]
https://babeljs.io/repl/

**Comment by ynunokawa** [comment]
[React入門(2)：reactify + watchify(browserify) + gulpでJSXを自動ビルドする](http://blog.takanabe.tokyo/2015/05/23/663/)

**Comment by ynunokawa** [comment]
TODO No.4 is developed on private environment.
